---
- name: installing tomcat server
  hosts: all
  become: yes
  tasks:
   - name: installing java
     apt:
       name: openjdk-8-jdk
       update_cache: yes
       state: present 
   - name: adding group
     group:
        name: tomcat
        state: present

  

      
      

    
  
    
   
    
    


  