---
- name: installing tomcat server
  hosts: all
  become: yes
  tasks:
   - name: installing java
     apt:
       name: openjdk-8-jdk
       update_cache: yes
       state: present 
   - name: adding group
     group:
        name: tomcat
        state: present
   - name: adding user
     user:
       name: tomcat
       state: present
       shell: /bin/false
       group: tomcat
       home: /opt/tomcat
   - name: insatalling unzip package
     apt:
       name: unzip 
       state: present 
   - name: installing wget package
     apt:
       name: wget
       state: present
   - name: downloading the tomcat zip file
     get_url:
        url: http://www-eu.apache.org/dist/tomcat/tomcat-9/v9.0.27/bin/apache-tomcat-9.0.27.tar.gz
        dest: /tmp/apache-tomcat-9.0.27.tar.gz






  

      
      

    
  
    
   
    
    


  