---
- name: installing tomcat server
  hosts: all
  become: yes
  tasks:
   - name: installing java
     apt:
       name: openjdk-8-jdk
       update_cache: yes
       state: present 
   - name: adding group
     group:
        name: tomcat
        state: present
   - name: adding user
     user:
       name: tomcat
       state: present
       shell: /bin/false
       group: tomcat
       home: /opt/tomcat
   - name: insatalling unzip package
     apt:
       name: unzip 
       state: present 
   - name: installing wget package
     apt:
       name: wget
       state: present
   - name: downloading the tomcat zip file
     get_url:
        url: https://downloads.apache.org/tomcat/tomcat-8/v8.5.65/bin/apache-tomcat-8.5.65.tar.gz
        dest: /tmp/apache-tomcat-8.5.65.tar.gz
   - name: unziping the tomcat file
     unarchive:
        src: /tmp/apache-tomcat-8.5.65.tar.gz
        dest: /opt/tomcat
   - name: creating create a symbolic link 
     file:
       src: /opt/tomcat/apache-tomcat-8.5.65
       dest: /opt/tomcat/latest
       owner: tomcat
       group: tomcat
       state: link
   - name: changing ownership
     file:
       path: /opt/tomcat/apache-tomcat-8.5.65
       owner: tomcat
       group: tomcat
       recurse: yes
   - name: giving file permissions
     file:
       path: "{{ item }}"
       owner: tomcat
       group: tomcat
       mode: "777"
     loop:
       - /opt/tomcat/latest/bin/catalina.sh
       - /opt/tomcat/latest/bin/ciphers.sh
       - /opt/tomcat/latest/bin/configtest.sh
       - /opt/tomcat/latest/bin/digest.sh
       - /opt/tomcat/latest/bin/tool-wrapper.sh
       - /opt/tomcat/latest/bin/daemon.sh  
       - /opt/tomcat/latest/bin/setclasspath.sh 
       - /opt/tomcat/latest/bin/startup.sh  
       - /opt/tomcat/latest/bin/shutdown.sh  
       - /opt/tomcat/latest/bin/version.sh
   - name: copying a file
     copy:
       src: tomcat.service
       dest: /etc/systemd/system/tomcat.service
   - name : reloading a demon
     systemd:
        name: tomcat
        enabled: yes
        daemon_reload: yes 
        state: "started"
     
       
   



      
 
 
       
    
                   
      







  

      
      

    
  
    
   
    
    


  